default_settings: null
behaviors:
  CarAgentContinuous:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      gail:
        strength: 0.75
        gamma: 0.99
        demo_path: Assets\demos\HowToRaceSix_0.demo
    behavioral_cloning:
      strength: 0.75
      gamma: 0.99
      demo_path: Assets\demos\HowToRaceSix_0.demo
    init_path: null
    keep_checkpoints: 10
    checkpoint_interval: 250000
    max_steps: 25000000
    time_horizon: 64
    summary_freq: 25000
    threaded: false
    self_play: null
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
environment_parameters: null
checkpoint_settings:
  run_id: ppo
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
